version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    groups:
      # Roll all action bumps into single pull request
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: "/terraform/proxmox"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
