- name: Configure all hosts
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common
  tags: common

- name: Configure Docker
  hosts: docker
  become: true
  roles:
    - docker
  tags: docker
