# https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/deb822_repository_module.html
- name: Add Docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}" # magic var

- name: Hold pinned Docker packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ docker_held_packages }}"

- name: Configure Docker daemon
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}\n"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker

- name: Start Docker and enable it at boot
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

- name: Allow users to run docker without sudo
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
